# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeformForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=200)),
                ('form_title', models.CharField(max_length=200)),
                ('event_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeformQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_id', models.CharField(max_length=1000)),
                ('ques_title', models.CharField(max_length=1000)),
                ('ques_type', models.CharField(max_length=1000)),
                ('ans_type', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
    ]
